In [7]:
%load_ext autoreload
%autoreload 2}

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
from meerkat.contrib.mimic import build_mimic_dp

In [10]:
dp = build_mimic_dp(
    dataset_dir="/home/common/datasets/mimic",
    gcp_project="hai-gcp-fine-grained",
    include_cxr_jpg = False,
    include_cxr_dicom= False,
    include_split=False
)

In [11]:
dp

DataPanel(num_rows: 377110)